import Link from 'next/link';
const sections:Record<string,{label:string;title:string;cards:{title:string;text:string}[];link:string;cta:string}>={
home:{label:'A little guidance',title:'Your first taste of Nepal',cards:[{title:'Start with momo',text:'Steamed, pan-fried, in a sesame-tomato jhol, or tossed in chilli sauce. Discover the dumpling at the heart of our menu.'},{title:'Make it a meal',text:'Explore aromatic curries, Himalayan noodle soup, and traditional Khaja Set platters with a selection of sides.'},{title:'Something to sip',text:'Stay for a masala chai, mango lassi, or a Himalayan-inspired cocktail from our full-service bar.'}],link:'/drinks',cta:'Explore drinks & bar'},
menu:{label:'Find your favourite',title:'A few ways to enjoy the menu',cards:[{title:'For the table',text:'Start with samosa or a sadeko salad, then share a Grand Momo Fest with three different momo preparations.'},{title:'Comfort in a bowl',text:'Try a warming Thukpa noodle soup or a slow-simmered goat curry with basmati rice on the side.'},{title:'Make it yours',text:'Momo comes with vegetable, chicken, or buffalo filling. Ask our team about ingredients and dietary requirements.'}],link:'/drinks',cta:'Find a drink to pair'},
drinks:{label:'Stay a little longer',title:'Find your perfect pairing',cards:[{title:'Creamy & comforting',text:'Mango lassi pairs with Butter Chicken, Paneer Jalfrezi, and Chilli Momo.'},{title:'Fresh & bright',text:'Try Himalayan Mohi or Saffron Cardamom Lemonade alongside Khaja Set, Chatpate, or Sukuti Sadeko.'},{title:'Warm & aromatic',text:'Enjoy Himalayan masala milk tea, black tea, or green tea to round out your meal.'}],link:'/menu',cta:'Back to the food menu'},
about:{label:'What brings us together',title:'Rooted in food. Made for people.',cards:[{title:'Himalayan inspiration',text:'Our menu brings together Nepali traditions and the diverse flavours of the Himalayas.'},{title:'Cooking with care',text:'Quality ingredients, aromatic spices, and recipes prepared with the attention of our experienced kitchen team.'},{title:'A welcome for everyone',text:'A familiar taste of home for some, a first introduction to Nepali cuisine for others. There’s room for both at our table.'}],link:'/menu',cta:'Discover our food'},
catering:{label:'From the first idea to the table',title:'Let’s plan your gathering',cards:[{title:'01 · Tell us your plans',text:'Share your event date, location, guest count, and occasion with us by email or phone.'},{title:'02 · Choose your menu',text:'Talk through your favourite dishes, dietary needs, and buffet preferences with our team.'},{title:'03 · Confirm the details',text:'We’ll discuss availability, pricing, and arrangements with you before your booking is confirmed.'}],link:'mailto:namcheottawa@gmail.com?subject=Catering%20enquiry',cta:'Start a catering enquiry'},
visit:{label:'Make yourself at home',title:'Plan a visit that suits you',cards:[{title:'Dine with us',text:'Find us at 1230 Wellington St. W. Call (613) 761-1616 for current opening hours and same-day availability.'},{title:'Bring friends',text:'Request a table online. For groups larger than 20, please call so we can talk through your plans.'},{title:'Enjoy Namche at home',text:'Explore current availability and place your order through our dedicated online ordering website.'}],link:'https://online.namchekitchen.ca/',cta:'Order online'},
reservations:{label:'Before you visit',title:'A few helpful details',cards:[{title:'Your request, confirmed personally',text:'Submitting the form saves your request. Our team will contact you by phone or email to confirm your table.'},{title:'Plans can change',text:'Call (613) 761-1616 to change or cancel your request. Have your name and booking reference ready.'},{title:'Make the visit comfortable',text:'Include accessibility needs, dietary requirements, or a special occasion in the notes. Our team will discuss arrangements with you.'}],link:'/menu',cta:'Have a look at the menu'},
privacy:{label:'Your choices',title:'Simple controls, whenever you need them',cards:[{title:'Cookie preferences',text:'Use Cookie settings in the footer to review the essential cookies used by this website.'},{title:'Thoughtful motion',text:'Subtle animations help the pages feel fluid. The website respects your device’s reduced-motion accessibility setting.'},{title:'Your booking details',text:'Contact namcheottawa@gmail.com to request a correction or deletion of your reservation information.'}],link:'mailto:namcheottawa@gmail.com',cta:'Contact us about privacy'}
};
export default function PageSections({page}:{page:string}){const content=sections[page];if(!content)return null;return <section className="extra-section section-pad"><div className="extra-heading"><span className="eyebrow">{content.label}</span><h2>{content.title}</h2></div><div className="info-grid">{content.cards.map(card=><article key={card.title}><h3>{card.title}</h3><p>{card.text}</p></article>)}</div><Link className="text-link" href={content.link}>{content.cta} <span aria-hidden="true">↗</span></Link></section>}
