import { cookies } from 'next/headers';
import { createHash, randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';
import { sql } from './db';
export const digest=(value:string)=>createHash('sha256').update(value).digest('hex');
export function hashPassword(password:string){const salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(password,salt,64).toString('hex');}
export function verifyPassword(password:string,stored:string){try{const [salt,hash]=stored.split(':');const expected=Buffer.from(hash,'hex');const actual=scryptSync(password,salt,64);return expected.length===actual.length&&timingSafeEqual(expected,actual);}catch{return false;}}
export async function session(){const token=(await cookies()).get('namche_session')?.value;if(!token)return null;const rows=await sql`select a.id,a.username from namche.sessions s join namche.admins a on a.id=s.admin_id where s.token_hash=${digest(token)} and s.expires_at>now()`;return rows[0]||null;}
export async function createSession(adminId:string){const token=randomBytes(32).toString('hex');await sql`delete from namche.sessions where expires_at<now()`;await sql`insert into namche.sessions(token_hash,admin_id,expires_at) values(${digest(token)},${adminId},now()+interval '8 hours')`;const jar=await cookies();jar.set('namche_session',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',path:'/',maxAge:28800});}
export function sameOrigin(request:Request){const origin=request.headers.get('origin');if(!origin)return false;try{const parsed=new URL(origin);if(!['http:','https:'].includes(parsed.protocol))return false;if(process.env.APP_ORIGIN)return parsed.origin===new URL(process.env.APP_ORIGIN).origin;return parsed.host===request.headers.get('host');}catch{return false;}}
export async function rateLimit(key:string,max:number,minutes:number){const result=await sql`insert into namche.rate_limits(key,count,expires_at) values(${key},1,now()+${minutes}*interval '1 minute') on conflict(key) do update set count=case when namche.rate_limits.expires_at<now() then 1 else namche.rate_limits.count+1 end,expires_at=case when namche.rate_limits.expires_at<now() then excluded.expires_at else namche.rate_limits.expires_at end returning count`;return result[0].count<=max;}
