import fs from 'node:fs/promises';
import postgres from 'postgres';
import sharp from 'sharp';
const sql=postgres(process.env.DATABASE_URL,{ssl:'require',max:2});
const reviews=[
 {id:'mamta-pandey',name:'MamAta PANDEY',file:'Mamta Pandey.png',excerpt:'The people there are truly wonderful, so warm and welcoming. Such a lovely experience overall!',body:'Loved Namche! The momo, chow-mein, and chai were all amazing,full of flavor and made with care. The people there are truly wonderful, so warm and welcoming. Such a lovely experience overall! definitely worth a visit!'},
 {id:'aavash-bhandari',name:'Aavash Bhandari',file:'Aavash Bhandari.png',excerpt:'The chicken momo were juicy, flavorful, and perfectly cooked. The jhol momo was rich and comforting, and the chowmein had an amazing smoky wok flavor.',body:'Took my Indian friends here to try authentic Nepali food and it was absolutely worth it. The chicken momo were juicy, flavorful, and perfectly cooked. The jhol momo was rich and comforting, and the chowmein had an amazing smoky wok flavor. The best part is they also serve buff momo, which is great for people looking for an authentic Nepali momo experience. Everyone loved the food, ambience, and overall vibe. Easily a 10/10 place for momo and chowmein.'},
 {id:'bibek-nepal',name:'Bibek Nepal',file:'Bibek Nepal.png',excerpt:'The atmosphere was nice and comfortable, and the people were very kind and welcoming. I really appreciate the good service.',body:'I had a great experience here. The momo and chow mein were very tasty and fresh. The atmosphere was nice and comfortable, and the people were very kind and welcoming. I really appreciate the good service. I truly enjoyed the food and will definitely come back again. 😊 😜'},
 {id:'anand-kane',name:'Anand Kane',file:'Anand Kane.png',excerpt:'Amazing authentic momos. The chowmein and great too. Hakka noodles could’ve been better.',body:'Amazing authentic momos. The chowmein and great too. Hakka noodles could’ve been better. Plenty of street paid parking. There’s a high chair and a booster seat available too. Nice service. Would love to try shawarma next time'},
 {id:'manish-bhattarai',name:'Manish Bhattarai',file:'Manish Bhattarai.png',excerpt:'Tried Buff Momo and Buff Chowmin Taste Was Really Authentic Like it was on Nepal',body:'Food Taste Was Really wow😍\nTried Buff Momo and Buff Chowmin Taste Was Really Authentic Like it was on Nepal'}
];
try{await sql`create table if not exists namche.reviews(id text primary key,name text not null,excerpt text not null,body text not null,rating integer not null check(rating between 1 and 5),image_id text references namche.images(id),sort_order integer not null)`;
 for(const [index,r] of reviews.entries()){const imageId='review-'+r.id;const data=await sharp(await fs.readFile('Reviews/'+r.file)).resize(120,120).webp({quality:90}).toBuffer();await sql`insert into namche.images(id,mime,data) values(${imageId},'image/webp',${data}) on conflict(id) do nothing`;await sql`insert into namche.reviews(id,name,excerpt,body,rating,image_id,sort_order) values(${r.id},${r.name},${r.excerpt},${r.body},5,${imageId},${index}) on conflict(id) do nothing`;}
 console.log('Five supplied Google reviews and reviewer photos saved in Neon.');
}finally{await sql.end();}
