import postgres from 'postgres';
import fs from 'node:fs/promises';
const sql=postgres(process.env.DATABASE_URL_UNPOOLED||process.env.DATABASE_URL,{ssl:'require',max:1,connect_timeout:15});
const content={name:'Namche Kitchen',tagline:'The Taste of Nepal',phone:'(613) 761-1616',phone_link:'+16137611616',email:'namcheottawa@gmail.com',address:'1230 Wellington St. W, Ottawa, ON K1Y 3A1',city:'Ottawa',timezone:'America/Toronto',order_url:'https://online.namchekitchen.ca/',hero_image_id:'restaurant-outdoor-v2',chef_image_id:'chef',chef_name:'Shailesh Bhattarai',chef_title:'Head Chef',chef_experience_years:15,welcome_heading:'Namaste & Welcome to Namche Kitchen',welcome_message:'Authentic Nepali flavours, lovingly prepared and warmly served in the heart of Ottawa, Canada. We’re delighted to have you at our table.',about:['Welcome to Namche Kitchen, where the flavours, warmth, and hospitality of Nepal come to your table.','Inspired by the rich culinary traditions of Nepal and the diverse flavours of the Himalayas, we bring you authentic Nepali favourites prepared with fresh ingredients, aromatic spices, and a passion for good food.','From our beloved momo and comforting Thali to flavourful curries, noodles, biryani, snacks, and Himalayan-inspired dishes, every plate is prepared with care and served with the warmth of Nepali hospitality.','At Namche Kitchen, we believe food is more than a meal—it is a way to share culture, memories, and a taste of home.','Whether you are discovering Nepali cuisine for the first time, missing the flavours of home, or simply looking for something delicious and different, we invite you to sit back, enjoy, and experience Nepal—one bite at a time. Thank you.'],chef_message:['Namaste and welcome to Namche Kitchen – The Taste of Nepal.','With 15 years of culinary experience, cooking is more than a profession to me—it is a passion and a way to share the flavours and traditions of Nepal.','At Namche Kitchen, I take pride in preparing authentic Nepali and Himalayan-inspired dishes using quality ingredients, traditional spices, and recipes made with care.','Whether you are enjoying a familiar taste of home or discovering Nepali cuisine for the first time, I hope every dish brings you a little taste of Nepal.','It is my pleasure and honour to cook for you.'],catering_min_guests:15,catering_max_guests:375,opening_hours:null};
try{await sql`create table if not exists namche.site_content(key text primary key,value jsonb not null,updated_at timestamptz not null default now())`;await sql`insert into namche.site_content(key,value) values('restaurant',${sql.json(content)}) on conflict(key) do update set value=excluded.value,updated_at=now()`;
 const counts=await sql`select 'Food items' as resource,count(*)::int as count from namche.menu_items where kind='food' union all select 'Beverages',count(*)::int from namche.menu_items where kind='drink' union all select 'Images',count(*)::int from namche.images union all select 'Reviews',count(*)::int from namche.reviews union all select 'Admin accounts',count(*)::int from namche.admins union all select 'Site content',count(*)::int from namche.site_content`;
 const updates=await sql`select name,price from namche.menu_items where name like 'Chatpate%' or name like 'Sukuti%' or name like 'Chicken Sadeko%' or name like 'Chicken Khaja%' or name like 'Thukpa%' or name like 'Kothey%' or name like 'Mutton%' order by sort_order`;
 const invalid=await sql`select m.id from namche.menu_items m left join namche.images i on i.id=m.image_id where m.image_id is not null and i.id is null`;
 if(invalid.length)throw new Error('Broken menu image references');
 const report={verified_at:new Date().toISOString(),project:'falling-tooth-21755546',branch:'production',counts,updated_prices:updates,broken_image_references:invalid.length};
 await fs.mkdir('test-results',{recursive:true});await fs.writeFile('test-results/neon-verification.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await sql.end();}
